{{- if and .Values.transport.http.enabled (and .Values.transport.http.serviceAccount.create) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thingsboard.transport.http.serviceAccount.name" . }}
  labels:
  {{- include "thingsboard.transport.http.labels" . | nindent 4 }}
  {{- with .Values.transport.http.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
