{{- if and .Values.js.enabled (and .Values.js.serviceAccount.create) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thingsboard.js.serviceAccount.name" . }}
  labels:
  {{- include "thingsboard.js.labels" . | nindent 4 }}
  {{- with .Values.js.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
