{{- if .Values.transport.mqtt.enabled -}}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.transport.mqtt.transportService.annotations }}
  annotations:
  {{ toYaml .Values.transport.mqtt.transportService.annotations | nindent 4 }}
  {{- end }}
  labels:
  {{- include "thingsboard.transport.mqtt.labels" . | nindent 4 }}
  {{- if .Values.transport.mqtt.transportService.labels }}
  {{ toYaml .Values.transport.mqtt.transportService.labels | nindent 4 }}
  {{- end }}
  name: {{ template "thingsboard.transport.mqtt.fullname" . }}
  {{ include "thingsboard.namespace" . | nindent 2 }}
spec:
  ports:
    - name: {{ .Values.transport.mqtt.transportService.servicePort.name }}
      port: {{ .Values.transport.mqtt.transportService.servicePort.port }}
      targetPort: {{ .Values.transport.mqtt.transportService.servicePort.targetPort }}
      protocol: TCP
  selector:
  {{- include "thingsboard.transport.mqtt.matchLabels" . | nindent 4 }}
  type: "{{ .Values.transport.mqtt.transportService.type }}"
{{- end -}}

