{{- if and .Values.node.enabled (and .Values.node.serviceAccount.create) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thingsboard.node.serviceAccount.name" . }}
  labels:
  {{- include "thingsboard.node.labels" . | nindent 4 }}
  {{- with .Values.node.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
